### ISSUE TITLE
support SPM

### ISSUE THREAD

**Issue by antranapp** [treatwell/twuitests#14]
Since Swifter also supports SPM, I think it is also useful when twuitests also supports SPM.

**Comment by lokatorius** [comment]
Hi,

Thank you for the idea. Yes, it would make sense to support SPM as our only dependency `Swifter` also supports it.

We will consider implementing support for it 👍

**Comment by treatwell-marius** [comment]
Swift Package Manager support has been added in [version 0.20.0](https://github.com/treatwell/twuitests/releases/tag/0.20.0)
